### ISSUE TITLE
文件写入问题

### ISSUE THREAD

**Issue by ResonanceForge** [vpei/free-node-1#1]
为什么我fork并运行之后配置文件没有改变？
[https://github.com/errorduplicator/clash_nodes/blob/main/o/clash.yaml](url)

**Comment by ResonanceForge** [comment]
### 原repo是不是也有这种问题？
_现在是北京时间2/19 12:30，23分钟之前更新过，配置文件好像并未改变_

**Comment by vpei** [comment]
> ### 原repo是不是也有这种问题？
> 
> _现在是北京时间2/19 12:30，23分钟之前更新过，配置文件好像并未改变_

node.json文件中的采集节点有些旧了，他们不更新也没办法，这个需要自己收集一些新的节点网址填充进去。
